Traceback (most recent call last):
  File "/home/mblab/ykang/proj_db_infer_pipe/scripts/generate_paired_fasta.py", line 58, in <module>
    main(sys.argv)
  File "/home/mblab/ykang/proj_db_infer_pipe/scripts/generate_paired_fasta.py", line 54, in main
    (query_header, query_dbd, all_headers[i], all_dbds[i], query_dbd))
UnboundLocalError: local variable 'query_header' referenced before assignment

FATAL: Sequence file contains no data
